name: user_log
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  shared_preferences: ^0.5.12+4
  flutter:
    sdk: flutter
  cache_image: ^1.0.5
  cupertino_icons: ^0.1.3
  flutter_spinkit: ^4.1.2
  http: ^0.12.2
  mockito: ^4.1.0
  provider: ^4.1.3

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.14.4

flutter:
  uses-material-design: true
